name: Build and Deploy Java App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: calculation-api-project

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: calculation1
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: calculation-api-project/target/*.jar
